spring:
  application:
    name: api-gateway
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: aBear
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Sell?characterEncoding=utf-8
  jpa:
    show-sql: true
  rabbitmq:
    host: 139.224.134.209
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379
zuul:
  routes:
#    product: /myProduct/**
#  ignored-patterns:
##    - /myProduct/product/listForOrder
##    - /product/product/listForOrder
#    - /**/product/listForOrder
    myProduct:
      path: /myProduct/**
      serviceId: product
